Pyngo/urls.py
from django.urls import path
from .views import index, contact,services, all_notifications, about_us, contact_us, language

app_name = 'pyngo'

urlpatterns = [
    path('', index, name='index'),
    path('contact/', contact, name='contact'),
    path('services/', services, name='services'),
    path('all/notifications/', all_notifications, name='all_notifications'),
    path('about/us/', about_us, name='about_us'),
    path('contact/us/', contact_us, name='contact_us'),
    path('language/<str:lang>/', language, name='language'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('Pyngo.urls')),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
)

if settings.DEBUG:
    urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/include/footer.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% if LANGUAGE_CODE == 'fa' %}

<footer class="page-footer text-right">
    <div class="container">
      <div class="row" >
        <div class="col-lg-4 py-3">
          <a href="{% url 'pyngo:index' %}" ><img src="{% static 'assets/img/logo.png' %}" alt="pyngoweb" width="200" height="50"></a>
        </div>
        <div class="col-lg-4 py-3" style='direction:rtl'>
          <p class='h4'>آدرس و ارتباط با پینگو وب</p>
          <p style='text-align:justify'><span class="mai-location fg-danger p-2"></span>سنندج - میدان انقلاب - خیابان امام - مجتمع خرمی - طبقه دوم - شرکت فنی و مهندسی پینگو وب </p>
          <p><span style="float:right" class="mai-mail fg-danger"></span> <a href="gmail:pyngoweb@gmail.com" class="fg-primary p-2">pyngoweb@gmail.com</a></p>

          <p><span style="float:right" class="mai-call fg-danger"> </span>  <a href="tel:08733178466" class="fg-primary p-2"> 087-33178466</a></p>

        </div>
        <div class="col-lg-4 py-3" >
          <h5>شرکت فنی و مهندسی</h5>
          <ul class="footer-menu">
            <li><a href="{% url 'pyngo:index' %}">pyngoweb.ir</a></li>
            <li><a >خصوصی</a></li>
            <li><a >حقوقی</a></li>
          </ul>
        </div>
        
      </div>

      <hr>

      <div class="row mt-4">
        <div class="col-md-6">
          <p>طراحی و ساخت از شرکت فنی و مهندسی <a href="{% url 'pyngo:index' %}">پینگو وب</a></p>
        </div>
        <div class="col-md-6 text-right">
          <div class="sosmed-button">
            <a href="#"><span class="mai-logo-instagram"></span></a>
            <a href="#"><span class="mai-logo-twitter"></span></a>
            <a href="#"><span class="mai-logo-youtube"></span></a>
            <a href="#"><span class="mai-logo-linkedin"></span></a>
          </div>
        </div>
      </div>
    </div>
  </footer>
 {% endif %}

{% if LANGUAGE_CODE == 'en' %}
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col-md-4 py-3">
        <a href="{% url 'pyngo:index' %}" ><img src="{% static 'assets/img/logo.png' %}" alt="pyngoweb" width="200" height="50"></a>
      </div>
      <div class="col-lg-4 py-3">
        <h5>Contact Information</h5>
        <p><span class="mai-location fg-danger p-2"></span> Iran, kurdestan, Sananndaj, Revolution Square, Imam Street</p>
        <p><span class="mai-mail fg-danger"></span> <a href="gmail:pyngoweb@gmail.com" class="fg-primary p-2">pyngoweb@gmail.com</a></p>

          <p><span class="mai-call fg-danger"> </span>  <a href="tel:+989188688569" class="fg-primary p-2"> +989188688569</a></p>

      </div>
      <div class="col-lg-4 py-3">
        <h5>Company</h5>
        <ul class="footer-menu">
          <li><a href="{% url 'pyngo:index' %}">pyngoweb.ir</a></li>
          <li><a>Private Company</a></li>
          <li><a>Special Company</a></li>
        </ul>
      </div>
    <hr>

    <div class="row mt-4">
      <div class="col-md-6">
        <p>This template designed by <a href="{% url 'pyngo:index' %}">pyngoweb</a></p>
      </div>
      <div class="col-md-6 text-left">
        <div class="sosmed-button">
          <a href="#"><span class="mai-logo-instagram"></span></a>
          <a href="#"><span class="mai-logo-twitter"></span></a>
          <a href="#"><span class="mai-logo-youtube"></span></a>
          <a href="#"><span class="mai-logo-linkedin"></span></a>
        </div>
      </div>
    </div>
  </div>
</footer>
{% endif %}

templates/include/header.html
{% load static %}
{% load notifications_tags %}
{% notifications_unread as unread_count %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% url 'pyngo:index' as index%}
{% url 'pyngo:services' as services%}
{% url 'pyngo:about_us' as about_us%}
{% url 'pyngo:portfolio' as portfolio%}
{% url 'pyngo:contact_us' as contact_us%}


{% if LANGUAGE_CODE == 'fa' %}
<header id='header'>
    <div class="top-bar bg-primary">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-8">
            <div class="d-inline-block">
              <span class="mai-call fg-light"> </span>  <a href="tel:08733178466" class="fg-light pl-2"> 087-33178466</a>
            </div>

            <div class="d-inline-block ml-2 fg-danger">
              <span class="dropdown-toggle" type="text" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <a href="" class='fg-danger' > فارسی</a>
              </span>
              <div class="dropdown-menu bg-primary">
                <a class="fg-light ml-2" href="{% url 'pyngo:language' 'fa' %}?next={{ request.get_full_path }}"> زبان فارسی </a>  <br>
                <a class="fg-light ml-2" href="{% url 'pyngo:language' 'en' %}?next={{ request.get_full_path }}">English language</a> 
              </div>
            </div>

            {% if request.user.is_authenticated and request.user.is_admin %}
          
            <div class="d-inline-block">
              <a href="{% url 'pyngo:all_notifications' %}" class="fg-light">
                <span class="mai-notifications ml-3 fg-danger"></span> 
                {% if unread_count > 0 %}
                  {{ unread_count }}
                {% else %}
                  0
                {% endif %}
              </a>
            </div>
            {% endif %}
            <div class="d-inline-block ml-2">
            </div>
          </div>
          <div class="col-md-4 text-right d-none d-md-block">
            <div class="social-mini-button">
              <a href="https://api.whatsapp.com/send?phone=989188688569"><span class="mai-logo-whatsapp fg-light"></span></a>
              <a href="#"><span class="mai-logo-telegram fg-light"></span></a>
              <a href="#"><span class="mai-logo-youtube fg-light"></span></a>
              <a href="https://www.instagram.com/pyngoweb/"><span class="mai-logo-instagram fg-light"></span></a>
            </div>
          </div>
        </div>
      </div> <!-- .container -->
    </div> <!-- .top-bar -->

    <nav class="navbar navbar-expand-md navbar-light" id='navbar_top' style="direction: rtl;">
      <div class="container">
        <a href="{{index}}" class="navbar-brand"><img src="{% static 'assets/img/logo.png' %}" alt="pyngoweb" width="150" height="30"></a>

        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse collapse" id="navbarContent">
          <ul class="navbar-nav ml-auto pt-3 pt-lg-0">
            <li class="nav-item {% if request.path == index %}active{% endif %}">
              <a href="{{ index }}" class="nav-link">صفحه اصلی</a>
            </li>
            
            <li class="nav-item {% if request.path == services %}active{% endif %}">
              <a href="{{services}}" class="nav-link">خدمات</a>
            </li>
           
            <li class="nav-item {% if request.path == contact_us %}active{% endif %}">
                <a href="{{contact_us}}" class="nav-link">تماس با ما</a>
            </li>
            <li class="nav-item {% if request.path == about_us %}active{% endif %}">
                <a href="{{about_us}}" class="nav-link">درباره ما</a>
            </li>
          </ul>
        </div>
       
      </div> <!-- .container -->
    </nav> <!-- .navbar -->
</header>

{% endif %}

{%if LANGUAGE_CODE == 'en' %}
<header id="header">
  <div class="top-bar bg-primary">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-md-8">
          <div class="d-inline-block">
            <span class="mai-call fg-light"> </span>  <a href="tel:+989188688569" class="fg-light pl-2"> +98-9188688569</a>
          </div>
          <div class="d-inline-block ml-2 fg-danger">
            <span class="dropdown-toggle" type="text" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             <a href="" class='fg-danger' >English</a>
            </span>
            <div class="dropdown-menu bg-primary">
              <a class="fg-light ml-2" href="{% url 'pyngo:language' 'fa' %}?next={{ request.get_full_path }}"> زبان فارسی </a>  <br>
              <a class="fg-light ml-2" href="{% url 'pyngo:language' 'en' %}?next={{ request.get_full_path }}">English language</a> 
            </div>
          </div>
          {% if request.user.is_authenticated and request.user.is_admin %}
          <div class="d-inline-block">
            <a href="{% url 'pyngo:all_notifications' %}" class="fg-light">
              <span class="mai-notifications ml-3 fg-danger"></span> 
              {% if unread_count > 0 %}
                {{ unread_count }}
              {% else %}
                0
              {% endif %}
            </a>
          </div>
          {% endif %}
          <div class="d-inline-block ml-2">
          </div>
        </div>
        <div class="col-md-4 text-right d-none d-md-block">
          <div class="social-mini-button">
            <a href="https://api.whatsapp.com/send?phone=989188688569"><span class="mai-logo-whatsapp fg-light"></span></a>
            
            <a href="#"><span class="mai-logo-telegram fg-light"></span></a>
            <a href="#"><span class="mai-logo-youtube fg-light"></span></a>
            <a href="https://www.instagram.com/pyngoweb/"><span class="mai-logo-instagram fg-light"></span></a>
          </div>
        
        </div>
      </div>
    </div> <!-- .container -->
  </div> <!-- .top-bar -->

  <nav class="navbar navbar-expand-md navbar-light" id="navbar_top">
    <div class="container">
      <a href="{{index}}" class="navbar-brand"><img
        src="{% static 'assets/img/logo.png' %}" alt="pyngoweb" width="150" height="30"></a>

      <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse collapse" id="navbarContent">
        <ul class="navbar-nav ml-auto pt-3 pt-lg-0">
          <li class="nav-item {% if request.path == index %}active{% endif %}">
            <a href="{{ index }}" class="nav-link">home page</a>
          </li>
          
          <li class="nav-item {% if request.path == services %}active{% endif %}">
            <a href="{{services}}" class="nav-link">services</a>
          </li>
         
          <li class="nav-item {% if request.path == contact_us %}active{% endif %}">
              <a href="{{contact_us}}" class="nav-link">contact us</a>
          </li>
          <li class="nav-item {% if request.path == about_us %}active{% endif %}">
              <a href="{{about_us}}" class="nav-link">about us</a>
          </li>
        </ul>
      </div>
      
    </div> <!-- .container -->
   
  </nav> <!-- .navbar -->
</header>
{% endif %}

templates/include/lang.html
{% load i18n %}
{% get_available_languages as LANGUAGES %}
{% get_language_info for LANGUAGE_CODE as lang %}

<div>
    <a href=""><i class='ti-world icon'>{{ lang.name_translated }}</i></a> <hr>
    {% for language_code, language_name in LANGUAGES %}
        <a href="{% url 'pyngo:language' language_code %}?next={{ request.get_full_path }}">{{ language_name }}</a>
    {% endfor %}
</div>

templates/include/msg.html
{% if messages %}
       {% for msg in messages %}
               <h4 class="col-md-12 text-center alert alert-{{ msg.tags }}">{{ msg }}</h4>
       {% endfor %}
{% endif %}